---
kind: pipeline
name: default

branches:
  - master
  - develop

steps:
- name: test
  image: php:7.2-cli
  commands:
    - composer install
    - composer test

- name: notification
  image: plugins/slack
  settings:
    webhook: https://hooks.slack.com/services/${HOOK_KEY}
    channel: notification
  environment:
    HOOK_KEY:
      from_secret: hook_key
